spring:
  application:
    name:
      Knyhozbirnia
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    open-in-view: true
    hibernate:
      ddl-auto: none

  cloud:
    gcp:
      sql:
      credentials:
        location: file:src/main/resources/credentials.json
  security:
    oauth2:
      client:
        registration:
            google:
#              redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
default:
  url:
    pfp:
      f: https://raw.githubusercontent.com/googlefonts/noto-emoji/main/png/512/emoji_u1f482_200d_2640.png
      m: https://raw.githubusercontent.com/googlefonts/noto-emoji/main/png/512/emoji_u1f482.png
      n: https://raw.githubusercontent.com/googlefonts/noto-emoji/main/png/512/emoji_u1f482_200d_2642.png
    frontend: http://localhost:3000


management:
  endpoint:
    sessions:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
          httptrace

metadata-location: metadata.json
